In [22]:
import numpy as np
import os
import utils.graph_utils as graph_utils
import utils.IO_utils as io_utils
import utils.plot_utils as plot_utils
import importlib
from sklearn import metrics

In [23]:
# reload module
importlib.reload(graph_utils)
importlib.reload(io_utils)
importlib.reload(plot_utils)

<module 'utils.plot_utils' from '/Users/anton/local/repos/ComE_BGMM/utils/plot_utils.py'>

In [24]:
input_file = "Dblp"

In [25]:
# load labels_true
labels_true, k = io_utils.load_ground_true(file_name=input_file+"/"+input_file)
labels_true = np.array(labels_true)

display(labels_true)

array([1, 3, 3, ..., 4, 5, 1])

In [26]:
# load labels_pred
labels_pred = np.loadtxt('./data/labels_pred.txt').astype(int)  #'./data/'+input_file+'/labels_pred.txt'

In [27]:
print("labels_true: ", labels_true)
print("labels_pred: ", labels_pred)

labels_true:  [1 3 3 ... 4 5 1]
labels_pred:  [2 2 2 ... 2 2 2]


In [28]:
print("labels_true:")
display(np.histogram(labels_true))

print("labels_pred:")
display(np.histogram(labels_pred))

labels_true:
labels_pred:


(array([2098,    0, 2167,    0,    0, 1973,    0, 5019,    0, 1927]),
 array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ]))

(array([4212,    0,  292,    0,    0, 8026,    0,  554,    0,  100]),
 array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. ]))

In [29]:
# NMI

metrics.normalized_mutual_info_score(labels_true, labels_pred)

0.2200479514944981